version: '3.8'

services:
  joyvite-postgres:
    image: postgres:15-alpine
    container_name: joyvite-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: JoyvitePassword123!
      POSTGRES_DB: joyvitedb
    ports:
      - "5432:5432"
    volumes:
      - joyvite-pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - joyvite-net

  joyvite-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: joyvite-backend
    environment:
      PORT: "3000"
      DATABASE_URL: "postgresql://admin:JoyvitePassword123!@joyvite-postgres:5432/joyvitedb?schema=public"
      MINIO_ENDPOINT: "minio-api.dayamedialangit.co.id"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "rahasia123"
      TEMPLATES_DIR: "/app/templates/Scraped_Templates"
    ports:
      - "3500:3000"
    volumes:
      - joyvite-templates:/app/templates
    depends_on:
      - joyvite-postgres
    restart: unless-stopped
    networks:
      - joyvite-net

volumes:
  joyvite-pgdata:
  joyvite-templates:

networks:
  joyvite-net:
    driver: bridge
